CREATE USER 'pitusas'@'%' IDENTIFIED WITH mysql_native_password AS 'Pitusas_2022_AR';GRANT ALL PRIVILEGES ON *.* TO 'pitusas'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE Database visitorbox character set utf-8;
USE visitorbox;

create table visitorbox
(
id int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(100),
email VARCHAR(100),
content TEXT NOT NULL,
date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
)
